package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

public class AdminController extends Controller{
	@FXML
	private Button pakomati;
	@FXML
	private Button kurjeri;
	@FXML
	private Button sutijumi;

	// Event Listener on Button[#pakomati].onAction
	@FXML
	public void pakomatiClicked(ActionEvent event) throws IOException {
		changeScene(pakomati, "/application/Pakomati.fxml");
	}
	// Event Listener on Button[#kurjeri].onAction
	@FXML
	public void kurjeriClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#sutijumi].onAction
	@FXML
	public void sutijumiClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
