package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class IzvelneController {
	@FXML
	private Button button_sanemt;
	@FXML
	private Button button_nosutit;
	
	private Stage myStage;
	private Scene myScene;
	private Parent root;

	// Event Listener on Button[#button_sanemt].onAction
	@FXML
	public void sanemtClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#button_nosutit].onAction
	@FXML
	public void nosutitClicked(ActionEvent event) throws IOException {
		root = FXMLLoader.load(getClass().getResource("/application/TestScene.fxml"));
		//myStage = (Stage)((Node)event.getSource()).getScene().getWindow();
		myStage = (Stage)button_nosutit.getScene().getWindow();
		myScene = new Scene(root);
		myStage.setScene(myScene);
		myStage.show();
	}
}
