package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

public class KautKasUnikalsController extends Controller {
	@FXML
	private Button button1;
	@FXML
	private Button BackButton1;

	// Event Listener on Button[#button1].onAction
	@FXML
	public void clickedButton1(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void backButtonClicked(ActionEvent event) throws IOException {
		changeScene(BackButton1, "/application/Izvelne.fxml");
	}
}
